# Generated by Django 5.1.4 on 2025-01-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomphoto',
            name='hotel',
        ),
    ]
