# Generated by Django 5.1.4 on 2025-01-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_hotel_price_remove_hotel_status_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='all_inclusive',
            field=models.BooleanField(default=True),
        ),
    ]
