# Generated by Django 5.1.4 on 2025-01-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_room_all_inclusive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='all_inclusive',
            field=models.TextField(),
        ),
    ]
